hwdec=vaapi
vo=gpu-next
sub-auto=fuzzy
keep-open=yes
autofit-smaller=540x540
ytdl-raw-options=cookies-from-browser=firefox,remote-components=ejs:github,js-runtimes=node,format-sort=res:720,compat-opt=prefer-vp9-sort
