#!/usr/bin/env python3
import os
import sys
from functools import partial
from http.server import SimpleHTTPRequestHandler, test


class Handler(SimpleHTTPRequestHandler):
    try_index = False

    def send_error(self, code, message=None):
        if code == 404 and not self.try_index:
            self.try_index = True
            self.path = '/index.html'
            self.do_GET()
        else:
            SimpleHTTPRequestHandler.send_error(self, code, message)


if __name__ == '__main__':

    directory = os.getcwd()
    if len(sys.argv) > 1:
        directory = sys.argv[1]

    port = 8080
    if len(sys.argv) > 2:
        port = int(sys.argv[2])

    handler_class = partial(Handler, directory=directory)
    test(HandlerClass=handler_class, port=port)
