#!/bin/sh
set -e

yay -Syu --combinedupgrade
echo '0' > "$HOME/.updates"
i3status_refresh
sudo find /var/cache/pacman/pkg -mindepth 1 -delete
find "$HOME/.cache/yay" -mindepth 1 ! -name 'completion.cache' -delete
